### ISSUE TITLE
Cannot use object of type DOMNodeList as array in  block_microsoft.php on line 193

### ISSUE THREAD

**Issue by jeyaprakashk** [Microsoft/moodle-block_microsoft#3]
Cannot use object of type DOMNodeList as array in /home/eceklu/public_html/elearn/blocks/microsoft/block_microsoft.php on line 193

**Comment by jeyaprakashk** [comment]
Changed the lines 193 and 194 as below: 
 $links->href=$delveurl;
                    $links->target='_blank';

**Comment by rlcharles** [comment]
What is your php version, libxml2 version and os that you are running on Moodle ?

**Comment by jeyaprakashk** [comment]
Running in a hosting server maintained by external agency.
OS: Linux 
Php: 5.6

**Comment by rlcharles** [comment]
You can get the full php info by logging in as a site admin and navigating to Site administration / ▶︎ Server / ▶︎ PHP info

The exact PHP version will be at the top, for example php 5.6.9.

There should be a section called dom, in that section there is libxml Version. What is the version ?

**Comment by jeyaprakashk** [comment]
PHP Version 5.6.22
libxml Version 	2.9.1

**Comment by rlcharles** [comment]
The php version and libxml are good, I've added this to our internal backlog.

**Comment by jamesmcq** [comment]
This should be resolved with the latest release, to be available here this Monday. The development repository has already released a fix here: https://github.com/Microsoft/o365-moodle
